### ISSUE TITLE
When importing causes a startup error (Bun)

### ISSUE THREAD

**Issue by Eveeifyeve** [ktym4a/astro-page-insight#137]
I have ran into this error when using bun for this when you import this package I run into this Error: 
```
6:27:01 PM [vite] Error when evaluating SSR module /Users/eveeifyeve/projects/TeaClient/Website/astro.config.ts: failed to import "astro-page-insight"
|- Error: could not find function name for: function(string, characterLimit) {
  return Util.truncate(string, characterLimit);
}
    at getRuntimeFunctionName (/Users/eveeifyeve/projects/TeaClient/Website/node_modules/lighthouse/core/lib/page-functions.js:263:20)
    at module code (/Users/eveeifyeve/projects/TeaClient/Website/node_modules/lighthouse/core/lib/page-functions.js:270:35)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at <anonymous> (:2:1)
    at processTicksAndRejections (:12:39)

[astro] Unable to load your Astro config

could not find function name for: function(string, characterLimit) {
  return Util.truncate(string, characterLimit);
}
  Stack trace:
    at getRuntimeFunctionName (/Users/eveeifyeve/projects/TeaClient/Website/node_modules/lighthouse/core/lib/page-functions.js:263:20)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at moduleEvaluation (:1:11)
    at <anonymous> (:2:1)
error: script "dev" exited with code 1
```

**Comment by Eveeifyeve** [comment]
repo to reproduce here: https://github.com/teaclientmc/website

**Comment by ktym4a** [comment]
Thanks for the report.

I'm not very familiar with bun, but from what I've found, it doesn't seem to be able to run lighthouse with bun right now.
https://github.com/oven-sh/bun/issues/4958

so I can't fix anything from this package at this time, so I'm closing it, sorry.

**Comment by ktym4a** [comment]
but I think it is accepted to work now (I just don't know what `atw` means well, though.)
https://github.com/oven-sh/bun/issues/8624
