### ISSUE TITLE
Shouldn't need chrome to do a Insight

### ISSUE THREAD

**Issue by Eveeifyeve** [ktym4a/astro-page-insight#67]
```
e-launcher/dist/utils.js:22:22)
    at new ChromeNotInstalledError (file:///Users/eveeify/Projects/TeaClient/Website/node_modules/chrome-launcher/dist/utils.js:49:9)
    at Launcher.launch (file:///Users/eveeify/Projects/TeaClient/Website/node_modules/chrome-launcher/dist/chrome-launcher.js:192:23)
    at Module.launch (file:///Users/eveeify/Projects/TeaClient/Website/node_modules/chrome-launcher/dist/chrome-launcher.js:33:20)
    at Module.startLH (/Users/eveeify/Projects/TeaClient/Website/node_modules/astro-page-insight/src/server/index.ts:10:46)
    at eval (/Users/eveeify/Projects/TeaClient/Website/node_modules/astro-page-insight/src/integration.ts:48:58)
    at file:///Users/eveeify/Projects/TeaClient/Website/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:60954:45
    at Set.forEach (<anonymous>)
    at WebSocket.<anonymous> (file:///Users/eveeify/Projects/TeaClient/Website/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:60954:23)
    at WebSocket.emit (node:events:514:28) {
  message: 'No Chrome installations found.',
  code: 'ERR_LAUNCHER_NOT_INSTALLED'
}
```
This is awkward I have arc that is a based on chromium also tryed it on firefox didn't work

**Comment by ktym4a** [comment]
Thanks for the issue!
I will add option to allow `chromePath` of `chrome-launcher` to be set.
but, I'm not sure that that will solve the problem.

> Same workaround fixes this issue if you only have Brave installed and no other Chromium-based browser (Mozilla's web-ext package uses chrome-launcher)

https://github.com/GoogleChrome/chrome-launcher/issues/208

**Comment by Eveeifyeve** [comment]
Also don't forget there is browsers like Firefox that other people use.

**Comment by Eveeifyeve** [comment]
In this case you could use something like https://pptr.dev if it works it install a chromium instance and it's very flexible

**Comment by ktym4a** [comment]
I didn't use `Puppeteer` because of the size, but will reconsider again.
Thanks for sharing.
